name: "Setup Node & Bun"
description: "Setup Node.js and Bun with dependency caching"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        node-version-file: '.node-version'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install Dependencies
      shell: bash
      run: bun install --frozen-lockfile
